#!/usr/bin/env python3
"""Wrap the built static mpv in a test dylib using its actual link dependencies.

This does not alter the distributed XCFramework. It exposes exactly the same
archive objects to the Python capture probe without a Flutter UI dependency.
"""

import argparse
from pathlib import Path
import shlex
import subprocess


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build", type=Path, required=True, help="mpv arm64 Meson scratch directory")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    build = args.build.resolve()
    output = args.output.resolve()
    lines = (build / "build.ninja").read_text().splitlines()
    index = next(i for i, line in enumerate(lines) if line.startswith("build mpv:"))
    linker = lines[index + 1]
    if not linker.startswith(" LINK_ARGS = "):
        raise RuntimeError("Upstream Meson link rule changed; inspect before adapting")
    # These are generated by our pinned, locally compiled sources; never accept
    # an arbitrary downloaded build.ninja. No shell interpretation is used.
    flags = shlex.split(linker.split(" = ", 1)[1])
    output.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["clang", "-dynamiclib", "-arch", "arm64", "-o", str(output),
                    "-Wl,-force_load," + str(build / "libmpv.a"), *flags], cwd=build, check=True)


if __name__ == "__main__":
    main()
