#!/usr/bin/env python3
"""Download and stage a completed fork-native Windows x64 build for the app.

The selected run must use this checkout's native lock and PCM patch.
The app commit may differ (Dart changes do not require rebuilding mpv).
Requires authenticated gh; keeps an auditable run/artifact/source/hash record.
"""

import argparse
import base64
import json
import os
import re
import shutil
import stat
import struct
import subprocess
import tempfile
import zipfile
from pathlib import Path, PurePosixPath

from prepare_native import MANIFEST, ROOT, digest

PATCH = "native/live_subtitle_sync/patches/0001-bounded-timestamped-pcm-tap.patch"
INPUTS = ("mpv-build.lock.json", PATCH)
MAX_EXPANDED = 512 * 1024 * 1024


def api(endpoint):
    return json.loads(subprocess.check_output(["gh", "api", endpoint], text=True))


def verify_run(repository, run_id):
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
        raise ValueError("Expected owner/repository")
    info = api(f"repos/{repository}/actions/runs/{run_id}")
    if (info["conclusion"] != "success" or info["status"] != "completed"
            or info["event"] != "workflow_dispatch"
            or info["path"] != ".github/workflows/livesync-mpv-build.yml"
            or info["head_repository"]["full_name"].lower() != repository.lower()):
        raise ValueError("Expected a successful native-build dispatch in this fork")
    sha = info["head_sha"]
    for name in INPUTS:
        remote = api(f"repos/{repository}/contents/{name}?ref={sha}")
        if base64.b64decode(remote["content"]) != (ROOT / name).read_bytes():
            raise ValueError(f"Native build inputs changed: {name}; rebuild mpv")
    artifacts = api(f"repos/{repository}/actions/runs/{run_id}/artifacts?per_page=100")
    matches = [item for item in artifacts["artifacts"]
               if item["name"] == f"livesync-mpv-windows-x64-{sha}" and not item["expired"]]
    if len(matches) != 1:
        raise ValueError("Expected exactly one unexpired Windows x64 native artifact")
    return info, matches[0]


def validate_pe(binary):
    if len(binary) < 64 or binary[:2] != b"MZ":
        raise ValueError("Native library is not a PE image")
    offset = struct.unpack_from("<I", binary, 0x3C)[0]
    if (offset + 6 > len(binary) or binary[offset:offset + 4] != b"PE\0\0"
            or struct.unpack_from("<H", binary, offset + 4)[0] != 0x8664):
        raise ValueError("Native library is not Windows x64")
    if b"livesync-enabled\0" not in binary or b"livesync-pcm\0" not in binary:
        raise ValueError("Native library does not expose the LiveSync PCM properties")


def stage(archive, destination, provenance):
    if destination.exists() and not (destination / "livesync-provenance.json").is_file():
        raise ValueError("Refusing to replace a directory not generated by LiveSync")
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mkdtemp(prefix=".livesync-mpv-", dir=destination.parent))
    try:
        with zipfile.ZipFile(archive) as bundle:
            entries = bundle.infolist()
            if sum(item.file_size for item in entries) > MAX_EXPANDED:
                raise ValueError("Native archive exceeds its expansion limit")
            seen = set()
            for item in entries:
                path = PurePosixPath(item.filename)
                mode = item.external_attr >> 16
                if (path.is_absolute() or ".." in path.parts or not path.parts
                        or "\\" in item.filename or ":" in item.filename
                        or stat.S_ISLNK(mode) or str(path).lower() in seen):
                    raise ValueError("Unexpected path in native archive")
                seen.add(str(path).lower())
            for name in ("libmpv-2.dll", "libmpv.dll.a", "include/mpv/client.h", "include/mpv/render.h"):
                if name not in seen:
                    raise ValueError(f"Incomplete native archive: {name}")
            bundle.extractall(temporary)
        validate_pe((temporary / "libmpv-2.dll").read_bytes())
        record = dict(provenance, architecture="x86_64", archiveSha256=digest(archive),
                      dllSha256=digest(temporary / "libmpv-2.dll"))
        (temporary / "livesync-provenance.json").write_text(json.dumps(record, indent=2) + "\n")
        if destination.exists():
            shutil.rmtree(destination)
        temporary.rename(destination)
    finally:
        if temporary.exists():
            shutil.rmtree(temporary)
    return record


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-id", type=int, required=True)
    parser.add_argument("--repository", default=os.environ.get("GITHUB_REPOSITORY", "DwennK/Plezy-SubtitleFix"))
    args = parser.parse_args()
    info, artifact = verify_run(args.repository, args.run_id)
    manifest = json.loads(MANIFEST.read_text())
    lock = json.loads((ROOT / "mpv-build.lock.json").read_text())
    if (lock["commit"] != manifest["native"]["commit"]
            or digest(ROOT / PATCH) != manifest["native"]["liveSyncPatchSha256"]):
        raise ValueError("Native manifest disagrees with current build inputs")
    with tempfile.TemporaryDirectory(prefix="livesync-win-download-") as scratch:
        subprocess.run(["gh", "run", "download", str(args.run_id), "--repo", args.repository,
                        "--name", artifact["name"], "--dir", scratch], check=True)
        archives = list(Path(scratch).glob("*.zip"))
        if len(archives) != 1:
            raise ValueError("Expected exactly one native dev zip")
        record = stage(archives[0], ROOT / "windows/LiveSyncMPV", {
            "nativeRevision": lock["commit"],
            "liveSyncPatchSha256": digest(ROOT / PATCH),
            "buildRepository": args.repository,
            "buildRun": args.run_id,
            "buildSourceSha": info["head_sha"],
            "buildUrl": info["html_url"],
            "artifactId": artifact["id"],
            "artifactDigest": artifact.get("digest"),
        })
    print(json.dumps(record, indent=2))


if __name__ == "__main__":
    main()
