#!/usr/bin/env python3
"""Stage the pinned MPVKit package with only its Libmpv binary replaced.

Run after the patched native build. Other binary URLs, checksums, sources and
linker settings come verbatim from the upstream commit selected by Plezy.
The generated package is local to macOS and does not change iOS or tvOS pins.
"""

import argparse
import json
import re
import shutil
import subprocess
import tempfile
import zipfile
from pathlib import Path, PurePosixPath

from prepare_native import ROOT, MANIFEST, digest, run


def stage(source, archive, checksum, destination):
    manifest = json.loads(MANIFEST.read_text())
    revision = manifest["native"]["commit"]
    lock = json.loads((ROOT / "mpv-build.lock.json").read_text())
    if lock["commit"] != revision:
        raise ValueError("Native lock changed: rebuild and update LiveSync provenance first")
    if run("git", "-C", str(source), "rev-parse", "HEAD") != revision:
        raise ValueError("Source checkout does not match the pinned native revision")
    if digest(archive) != checksum:
        raise ValueError("Patched XCFramework archive checksum mismatch")
    # Validate paths before invoking ditto, which preserves framework symlinks.
    with zipfile.ZipFile(archive) as bundle:
        for entry in bundle.infolist():
            parts = PurePosixPath(entry.filename).parts
            if not parts or parts[0] != "Libmpv.xcframework" or ".." in parts:
                raise ValueError("Unexpected path in Libmpv archive")
    package = run("git", "-C", str(source), "show", f"{revision}:Package.swift")
    pattern = r'\.binaryTarget\(\s*name: "Libmpv",\s*url: "[^"]+",\s*checksum: "[0-9a-f]{64}"\s*\)'
    package, count = re.subn(pattern, '.binaryTarget(name: "Libmpv", path: "Artifacts/Libmpv.xcframework")', package)
    if count != 1:
        raise ValueError("Upstream Libmpv target changed: review the package before adapting")
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists() and not (destination / "livesync-provenance.json").is_file():
        raise ValueError("Refusing to replace a directory not generated by LiveSync")
    temporary = Path(tempfile.mkdtemp(prefix=".livesync-mpv-", dir=destination.parent))
    try:
        (temporary / "Package.swift").write_text(package + "\n")
        files = run("git", "-C", str(source), "ls-tree", "-r", "--name-only", revision,
                    "Sources/_MPVKit", "Sources/_FFmpeg").splitlines()
        for name in files:
            output = temporary / name
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_bytes(subprocess.check_output(["git", "-C", str(source), "show", f"{revision}:{name}"]))
        subprocess.run(["ditto", "-x", "-k", str(archive), str(temporary / "Artifacts")], check=True)
        # A stock artifact must not accidentally masquerade as the patched one.
        binary = temporary / "Artifacts/Libmpv.xcframework/macos-arm64_x86_64/Libmpv.framework/Versions/A/Libmpv"
        if b"livesync-enabled\0" not in binary.read_bytes():
            raise ValueError("The native archive does not contain the LiveSync PCM property")
        (temporary / "livesync-provenance.json").write_text(json.dumps({
            "nativeRevision": revision,
            "xcframeworkSha256": checksum,
            "liveSyncPatchSha256": manifest["native"]["liveSyncPatchSha256"],
            "packageSource": "Pinned upstream Package.swift; only Libmpv target uses a local path",
        }, indent=2) + "\n")
        # Build inputs are generated and replaceable; refuse arbitrary directories above.
        if destination.exists():
            shutil.rmtree(destination)
        temporary.rename(destination)
    finally:
        if temporary.exists():
            shutil.rmtree(temporary)
    return destination


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--archive", type=Path, required=True)
    parser.add_argument("--sha256", required=True)
    args = parser.parse_args()
    if not re.fullmatch(r"[0-9a-f]{64}", args.sha256):
        parser.error("--sha256 must be the reviewed artifact's full SHA-256")
    print(stage(args.source.resolve(), args.archive.resolve(), args.sha256,
                ROOT / "macos/LiveSyncMPV"))


if __name__ == "__main__":
    main()
